package com.fmohammadi.covid19.model

import android.util.Log

fun getTranslate(key:String):String{
    val translateFA:HashMap<String , String> = HashMap()
    translateFA.put("Afghanistan","افغانستان")
    translateFA.put("Albania","آلبانی")
    translateFA.put("Algeria","الجزایر")
    translateFA.put("Andorra","آندورا")
    translateFA.put("Angola","آنگولا")
    translateFA.put("Anguilla","آنگویلا")
    translateFA.put("Antigua and Barbuda","آنتیگوا و باربودا")
    translateFA.put("Argentina","آرژانتین")
    translateFA.put("Armenia","ارمنستان")
    translateFA.put("Aruba","آروبا")
    translateFA.put("Australia","استرالیا")
    translateFA.put("Austria","اتریش")
    translateFA.put("Azerbaijan","آذربایجان")
    translateFA.put("Bahamas","باهاما")
    translateFA.put("Bahrain","بحرین")
    translateFA.put("Bangladesh","بنگلادش")
    translateFA.put("Barbados","باربادوس")
    translateFA.put("Belarus","بلاروس")
    translateFA.put("Belgium","بلژیک")
    translateFA.put("Belize","بلیز")
    translateFA.put("Benin","بنین")
    translateFA.put("Bermuda","برمودا")
    translateFA.put("Bhutan","بوتان")
    translateFA.put("Bolivia","بولیوی")
    translateFA.put("Bosnia","بوسنی")
    translateFA.put("Botswana","بوتسوانا")
    translateFA.put("Brazil","برزیل")
    translateFA.put("British Virgin Islands","جزایر ویرجین انگلیس")
    translateFA.put("Brunei","برونئی")
    translateFA.put("Bulgaria","بلغارستان")
    translateFA.put("Burkina Faso","بورکینافاسو")
    translateFA.put("Burundi","بوروندی")
    translateFA.put("Cabo Verde","کیپ ورد")
    translateFA.put("Cambodia","کامبوج")
    translateFA.put("Cameroon","کامرون")
    translateFA.put("Canada","کانادا")
    translateFA.put("Caribbean Netherlands","کارائیب هلند")
    translateFA.put("Cayman Islands","جزایر کیمن")
    translateFA.put("Central African Republic","جمهوری آفریقای مرکزی")
    translateFA.put("Chad","چاد")
    translateFA.put("Channel Islands","جزایر کانال")
    translateFA.put("Chile","شیلی")
    translateFA.put("China","چین")
    translateFA.put("Colombia","کلمبیا")
    translateFA.put("Comoros","کومور")
    translateFA.put("Congo","کنگو")
    translateFA.put("Costa Rica","کاستاریکا")
    translateFA.put("Croatia","کرواسی")
    translateFA.put("Cuba","کوبا")
    translateFA.put("Curaçao","کوراسائو")
    translateFA.put("Cyprus","قبرس")
    translateFA.put("Czechia","چکی")
    translateFA.put("Côte d'Ivoire","ساحل عاج")
    translateFA.put("DRC","جمهوری دموکراتیک کنگو")
    translateFA.put("Denmark","دانمارک")
    translateFA.put("Diamond Princess","دایموند پرینسس")
    translateFA.put("Djibouti","جیبوتی")
    translateFA.put("Dominica","دومینیکا")
    translateFA.put("Dominican Republic","جمهوری دومینیکن")
    translateFA.put("Ecuador","اکوادور")
    translateFA.put("Egypt","مصر")
    translateFA.put("El Salvador","السالوادور")
    translateFA.put("Equatorial Guinea","گینه استوایی")
    translateFA.put("Eritrea","اریتره")
    translateFA.put("Estonia","استونی")
    translateFA.put("Ethiopia","اتیوپی")
    translateFA.put("Falkland Islands (Malvinas)","جزایر فالکلند (مالویناس)")
    translateFA.put("Faroe Islands","جزایر فارو")
    translateFA.put("Fiji","فیجی")
    translateFA.put("Finland","فنلاند")
    translateFA.put("France","فرانسه")
    translateFA.put("French Guiana","گویان فرانسه")
    translateFA.put("French Polynesia"," پلی نزی فرانسه")
    translateFA.put("Gabon","گابن")
    translateFA.put("Gambia","گامبیا")
    translateFA.put("Georgia","گرجستان")
    translateFA.put("Germany","آلمان")
    translateFA.put("Ghana","غنا")
    translateFA.put("Gibraltar","جبل الطارق")
    translateFA.put("Greece","یونان")
    translateFA.put("Greenland","گرینلند")
    translateFA.put("Grenada","گرنادا")
    translateFA.put("Guadeloupe","جزیره گوادلوپ")
    translateFA.put("Guatemala","گواتمالا")
    translateFA.put("Guinea","گینه")
    translateFA.put("Guinea-Bissau","گینه بیسائو")
    translateFA.put("Guyana","گویان")
    translateFA.put("Haiti","جزیره هاییتی")
    translateFA.put("Holy See (Vatican City State)","واتیکان")
    translateFA.put("Honduras","هندوراس")
    translateFA.put("Hong Kong","هنگ کنگ")
    translateFA.put("Hungary","مجارستان")
    translateFA.put("Iceland","جزیره ایسلند")
    translateFA.put("India","هندوستان")
    translateFA.put("Indonesia","اندونزی")
    translateFA.put("Iran","ایران")
    translateFA.put("Iraq","عراق")
    translateFA.put("Ireland","ایرلند")
    translateFA.put("Isle of Man","جزیره من")
    translateFA.put("Israel","اسرائيل")
    translateFA.put("Italy","ایتالیا")
    translateFA.put("Jamaica","جامائیکا")
    translateFA.put("Japan","ژاپن")
    translateFA.put("Jordan","اردن")
    translateFA.put("Kazakhstan","قزاقستان")
    translateFA.put("Kenya","کنیا")
    translateFA.put("Kuwait","کویت")
    translateFA.put("Kyrgyzstan","قرقیزستان")
    translateFA.put("Lao People's Democratic Republic","جمهوری دموکراتیک خلق لائو")
    translateFA.put("Latvia","لتونی")
    translateFA.put("Lebanon","لبنان")
    translateFA.put("Lesotho","لسوتو")
    translateFA.put("Liberia","لیبریا")
    translateFA.put("Libyan Arab Jamahiriya","جاماهیریای عرب لیبی")
    translateFA.put("Liechtenstein","لیختن اشتاین")
    translateFA.put("Lithuania","لیتوانی")
    translateFA.put("Luxembourg","لوکزامبورگ")
    translateFA.put("MS Zaandam","ام اس زاندم")
    translateFA.put("Macao","ماکائو")
    translateFA.put("Macedonia","مقدونیه")
    translateFA.put("Madagascar","ماداگاسکار")
    translateFA.put("Malawi","مالاوی")
    translateFA.put("Malaysia","مالزی")
    translateFA.put("Maldives","مالدیو")
    translateFA.put("Mali","مالی")
    translateFA.put("Malta","جزیره مالت")
    translateFA.put("Martinique","مارتینیک")
    translateFA.put("Mauritania","موریتانی")
    translateFA.put("Mauritius","موریس")
    translateFA.put("Mayotte","مایوت")
    translateFA.put("Mexico","مکزیک")
    translateFA.put("Moldova","مولداوی")
    translateFA.put("Monaco","موناکو")
    translateFA.put("Mongolia","مغولستان")
    translateFA.put("Montenegro","مونته نگرو")
    translateFA.put("Montserrat","مونتسرات")
    translateFA.put("Morocco","مراکش")
    translateFA.put("Mozambique","موزامبیک")
    translateFA.put("Myanmar","میانمار")
    translateFA.put("Namibia","ناميبيا")
    translateFA.put("Nepal","نپال")
    translateFA.put("Netherlands","هلند")
    translateFA.put("New Caledonia","کالدونیای جدید")
    translateFA.put("New Zealand","نیوزلند")
    translateFA.put("Nicaragua","نیکاراگوئه")
    translateFA.put("Niger","نیجر")
    translateFA.put("Nigeria","نیجریه")
    translateFA.put("Norway","نروژ")
    translateFA.put("Oman","عمان")
    translateFA.put("Pakistan","پاکستان")
    translateFA.put("Palestine","فلسطین")
    translateFA.put("Panama","جمهوری پاناما")
    translateFA.put("Papua New Guinea","پاپوآ گینه نو")
    translateFA.put("Paraguay","پاراگوئه")
    translateFA.put("Peru","پرو")
    translateFA.put("Philippines","فیلیپین")
    translateFA.put("Poland","لهستان")
    translateFA.put("Portugal","پرتغال")
    translateFA.put("Qatar","قطر")
    translateFA.put("Romania","رومانی")
    translateFA.put("Russia","روسیه")
    translateFA.put("Rwanda","رواندا")
    translateFA.put("Réunion","رئونیون")
    translateFA.put("S. Korea","کره جنوبی")
    translateFA.put("Saint Kitts and Nevis","سنت کیتس و نویس")
    translateFA.put("Saint Lucia","سنت لوسیا")
    translateFA.put("Saint Martin","سن مارتین")
    translateFA.put("Saint Pierre Miquelon","سنت پیر میکلون")
    translateFA.put("Saint Vincent and the Grenadines","سنت وینسنت و گرنادین ها")
    translateFA.put("San Marino","سان مارینو")
    translateFA.put("Sao Tome and Principe","سائوتومه و پرینسیپ")
    translateFA.put("Saudi Arabia","عربستان سعودی")
    translateFA.put("Senegal","سنگال")
    translateFA.put("Serbia","صربستان")
    translateFA.put("Seychelles","سیشل")
    translateFA.put("Sierra Leone","سیرا لئون")
    translateFA.put("Singapore","سنگاپور")
    translateFA.put("Sint Maarten","سنت مارتین")
    translateFA.put("Slovakia","اسلواکی")
    translateFA.put("Slovenia","اسلوونی")
    translateFA.put("Somalia","سومالی")
    translateFA.put("South Africa","آفریقای جنوبی")
    translateFA.put("South Sudan","سودان جنوبی")
    translateFA.put("Spain","اسپانیا")
    translateFA.put("Sri Lanka","سری لانکا")
    translateFA.put("St. Barth","سنت بارت")
    translateFA.put("Sudan","سودان")
    translateFA.put("Suriname","سورینام")
    translateFA.put("Swaziland","سوازیلند")
    translateFA.put("Sweden","سوئد")
    translateFA.put("Switzerland","سوئیس")
    translateFA.put("Syrian Arab Republic","جمهوری عربی سوریه")
    translateFA.put("Taiwan","تایوان")
    translateFA.put("Tajikistan","تاجیکستان")
    translateFA.put("Tanzania","تانزانیا")
    translateFA.put("Thailand","تایلند")
    translateFA.put("Timor-Leste","تیمور شرقی")
    translateFA.put("Togo","توگو")
    translateFA.put("Trinidad and Tobago","ترینیداد و توباگو")
    translateFA.put("Tunisia","تونس")
    translateFA.put("Turkey","ترکیه")
    translateFA.put("Turks and Caicos Islands","جزایر ترک و کایکوس")
    translateFA.put("UAE","امارات متحده عربی")
    translateFA.put("UK","بریتانیا")
    translateFA.put("USA","ایالات متحده آمریکا")
    translateFA.put("Uganda","اوگاندا")
    translateFA.put("Ukraine","اوکراین")
    translateFA.put("Uruguay","اروگوئه")
    translateFA.put("Uzbekistan","ازبکستان")
    translateFA.put("Venezuela","ونزوئلا")
    translateFA.put("Vietnam","ویتنام")
    translateFA.put("Western Sahara","صحرای غربی")
    translateFA.put("Yemen","یمن")
    translateFA.put("Zambia","زامبیا")
    translateFA.put("Zimbabwe","زیمبابوه")
    return if(translateFA.containsKey(key))
        translateFA.get(key).toString()
    else
        key
}